### ISSUE TITLE
コーディング規約を遵守して記述する

### ISSUE THREAD

**Issue by norotime** [y-uesg/stocks_and_earnings#1]
https://github.com/y-uesg/stocks_and_earnings/blob/da35d9624f47ab62a151731b406cc14ec85cce45/app/models/user.rb#L10

@y-uesg インデントがずれていたり、不要な空行等がないか、全体を一度チェックしてくださいーー。
http://www.ruby.or.jp/ja/tech/development/ruby/050_coding_rule.html

**Comment by y-uesg** [comment]
Fixed #1
Rubyファイルを中心にインデントの統一、不要なコメントアウト行・空行の削除を行いました。

**Comment by norotime** [comment]
@y-uesg 素晴らしい！いいですね。
