### ISSUE TITLE
不必要なログ蓄積を防ぐため本番環境のログ設定は通常モードにしておく

### ISSUE THREAD

**Issue by norotime** [y-uesg/stocks_and_earnings#3]
https://github.com/y-uesg/stocks_and_earnings/blob/da35d9624f47ab62a151731b406cc14ec85cce45/config/environments/production.rb#L52

**Comment by y-uesg** [comment]
Fixed #3
ログモードを「:info」に修正しました

**Comment by norotime** [comment]
@y-uesg 素晴らしい！

**Comment by y-uesg** [comment]
レビューありがとうございます！
今回の１〜３までのイシューはクローズしても問題ないでしょうか？

いまいち理解が不完全なのですが、イシューのクローズは作成者がする方が良いでしょうか？

**Comment by norotime** [comment]
@y-uesg イシューは終わったらクローズしてください！

**Comment by norotime** [comment]
@y-uesg 自分でクローズするのはプルリクエストです。
